//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Notifications = new HashSet<Notification>();
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> state { get; set; }
        public byte[] ImageUS { get; set; }
        public string OrganizationID { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
