//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCategory
    {
        public EventCategory()
        {
            this.Events = new HashSet<Event>();
        }
    
        public string CategoryID { get; set; }
        public string CategoryImage { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> state { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
