//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string NotificationID { get; set; }
        public string NotificationContent { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string AccountID { get; set; }
        public Nullable<bool> state { get; set; }
        public byte[] NotiImg { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
