//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public string OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<bool> state { get; set; }
        public string COCK { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
