//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanHuyen
    {
        public QuanHuyen()
        {
            this.XaPhuongs = new HashSet<XaPhuong>();
        }
    
        public int ID { get; set; }
        public string tenQuanHuyen { get; set; }
        public int tinhThanhPhoId { get; set; }
    
        public virtual TinhThanhPho TinhThanhPho { get; set; }
        public virtual ICollection<XaPhuong> XaPhuongs { get; set; }
    }
}
