//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuocGia
    {
        public QuocGia()
        {
            this.TinhThanhPhoes = new HashSet<TinhThanhPho>();
        }
    
        public int ID { get; set; }
        public string tenQuocGia { get; set; }
    
        public virtual ICollection<TinhThanhPho> TinhThanhPhoes { get; set; }
    }
}
