//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public Ranking()
        {
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public string RankId { get; set; }
        public string RankName { get; set; }
        public byte[] RankImage { get; set; }
        public Nullable<int> PointRequire { get; set; }
        public Nullable<bool> state { get; set; }
    
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
