//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public string RegistrationID { get; set; }
        public string VolunteerID { get; set; }
        public string EventID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<bool> CheckIn { get; set; }
        public Nullable<bool> CheckOut { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<bool> state { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveAccountID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
