//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string ReviewID { get; set; }
        public string VolunteerID { get; set; }
        public Nullable<int> ReviewPoint { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string state { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
    }
}
