//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public Reward()
        {
            this.VolunteerRewards = new HashSet<VolunteerReward>();
        }
    
        public string RewardID { get; set; }
        public string RewardName { get; set; }
        public Nullable<int> RedeemPoint { get; set; }
        public Nullable<bool> state { get; set; }
        public byte[] RewardImg { get; set; }
    
        public virtual ICollection<VolunteerReward> VolunteerRewards { get; set; }
    }
}
