//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysIndex
    {
        public int ID { get; set; }
        public string Prefix { get; set; }
        public string IndexName { get; set; }
        public Nullable<int> currentIndex { get; set; }
    }
}
