//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhThanhPho
    {
        public TinhThanhPho()
        {
            this.QuanHuyens = new HashSet<QuanHuyen>();
        }
    
        public int ID { get; set; }
        public string tenTinhThanhPho { get; set; }
        public int quocGiaId { get; set; }
    
        public virtual ICollection<QuanHuyen> QuanHuyens { get; set; }
        public virtual QuocGia QuocGia { get; set; }
    }
}
